### PR TITLE
Master

### PR DESCRIPTION
**Pull request by anjuls**

### CODE REVIEW

**Comment by hyee** [comment]
Other parts are merged

**Comment by anjuls** [comment]
Yep, I can see..thanks.  Cool tool by the way... 
What next thing are you trying to add in this tool?

**Comment by hyee** [comment]
Mainly on bug fix and the chart scripts. If you have good ideas, welcome for your contribution. :P

**Comment by hyee** [comment]
I did some changes on the program name issue, user is able to customize the program name by setting the content of data\jdbc_url.cfg. For example:

```
return {
     oracle={["v$session.program"]="DBA Cockpit"}
}
```

And also is able to specify other jdbc properties in both global level and connection level, following links for references:
1. http://docs.oracle.com/cd/E18283_01/appdev.112/e13995/oracle/jdbc/pool/OracleDataSource.html#setConnectionProperties_java_util_Properties_
2. http://docs.oracle.com/database/121/JAJDB/constant-values.html#oracle_jdbc_OracleConnection_ACCESSMODE_BOTH

Thanks for your contribution.

**Pull request closed without merging**
